// Generated by CoffeeScript 1.4.0
(function() {
  var ActorType, MediaLinkType, mongoose, _;

  mongoose = require("mongoose");

  _ = require('underscore');

  MediaLinkType = {
    duration: Number,
    height: Number,
    width: Number,
    url: String
  };

  ActorType = {
    actorId: {
      type: String,
      required: true
    },
    displayName: {
      type: String,
      match: /.{0,100}/
    },
    image: {
      type: MediaLinkType
    }
  };

  exports.createdBy = function(schema, options) {
    if (!options) {
      options = {};
    }
    _.defaults(options, {
      isRequired: false
    });
    if (!options.defaultActor) {
      options.defaultActor = function() {
        return null;
      };
    }
    return schema.add({
      createdBy: {
        type: ActorType,
        "default": options.defaultActor,
        required: options.isRequired
      }
    });
  };

}).call(this);
